services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/yar4edb
      SPRING_DATASOURCE_USERNAME: yar4e
      SPRING_DATASOURCE_PASSWORD: yar4e
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yar4e
      POSTGRES_PASSWORD: yar4e
      POSTGRES_DB: yar4edb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: